kind: pipeline
name: internship-nodejs-api
type: docker

steps:
  - name: dokku-deploy
    image: dokku/ci-docker-image
    environment:
      SSH_PRIVATE_KEY:
        from_secret: DOKKU_DEPLOY_KEY
      GIT_REMOTE_URL:
        from_secret: DOKKU_DEPLOY_URL
      GIT_PUSH_FLAGS:
        from_secret: DOKKU_PUSH_FLAGS
    commands:
      - dokku-deploy
    when:
      branch:
      - master

  # - name: notify
  #   image: pelotech/drone-google-chat
  #   settings:
  #     webhook: https://chat.googleapis.com/v1/spaces/AAAAYcHAFlE
  #     key: AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI
  #     token: O3Lx3EgJO-DveaLkueVgn6pEsTPWy-Yi-kbOec1jOT4
  #     conversation_key: skills-fe
  #     template: >
  #       {{#success build.status}}
  #         <{{build.link}}|Build #{{build.number}} succeeded in {{since build.created}} for branch {{build.branch}}.>
  #       {{else}}
  #         <{{build.link}}|Build #{{build.number}} failed in {{since build.created}} for branch {{build.branch}}.>
  #       {{/success}}
  #   when:
  #     status:
  #     - success
  #     - failure

trigger:
  branch:
  - master
  event:
  - push