kind: pipeline
name: internship-nodejs-api
type: docker

steps:
  - name: dokku-deploy
    image: dokku/ci-docker-image
    environment:
      SSH_PRIVATE_KEY:
        from_secret: DOKKU_DEPLOY_KEY
      GIT_REMOTE_URL:
        from_secret: DOKKU_DEPLOY_URL
      GIT_PUSH_FLAGS:
        from_secret: DOKKU_PUSH_FLAGS
    commands:
      - dokku-deploy
    when:
      branch:
      - master

  - name: notify
    image: pelotech/drone-google-chat
    settings:
      webhook: https://chat.googleapis.com/v1/spaces/AAAAYcHAFlE
      key: AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI
      token: RaPEK4r4m3NtR5gNe02kGui6dDeC4DZ6XyWbHLsFCTM
      conversation_key: internship-nodejs-api
      template: >
        {{#success build.status}}
          <{{build.link}}|Build #{{build.number}}> succeeded in {{since build.created}} for branch {{build.branch}}, {{build.event}} by {{build.author}}.
        {{else}}
          <{{build.link}}|Build #{{build.number}}> failed in {{since build.created}} for branch {{build.branch}}, {{build.event}} by {{build.author}}.
        {{/success}}
    when:
      status:
      - success
      - failure

trigger:
  branch:
  - master
  event:
  - push